const actionTypes = {
  GET_CHEF_REQUEST: 'GET_CHEF_REQUEST',
  GET_CHEF_SUCCESS: 'GET_CHEF_SUCCESS',
  GET_CHEF_FAILURE: 'GET_CHEF_FAILURE',

  CHEF_UPDATE_REQUEST: 'CHEF_UPDATE_REQUEST',
  CHEF_UPDATE_SUCCESS: 'CHEF_UPDATE_SUCCESS',
  CHEF_UPDATE_FAILURE: 'CHEF_UPDATE_FAILURE',

  CHEF_NEW_REQUEST: 'CHEF_NEW_REQUEST',
  CHEF_NEW_SUCCESS: 'CHEF_NEW_SUCCESS',
  CHEF_NEW_FAILURE: 'CHEF_NEW_FAILURE',

  CHEF_DELETE_REQUEST: 'CHEF_DELETE_REQUEST',
  CHEF_DELETE_SUCCESS: 'CHEF_DELETE_SUCCESS',
  CHEF_DELETE_FAILURE: 'CHEF_DELETE_FAILURE',

  RATE_CHEF_REQUEST: 'RATE_CHEF_REQUEST',
  RATE_CHEF_SUCCESS: 'RATE_CHEF_SUCCESS',
  RATE_CHEF_FAILURE: 'RATE_CHEF_FAILURE',

  CHEF_CHANGE_DATA: 'CHEF_CHANGE_DATA',
};

export default actionTypes;