const actionTypes = {
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

  USER_NEW_REQUEST: 'USER_NEW_REQUEST',
  USER_NEW_SUCCESS: 'USER_NEW_SUCCESS',
  USER_NEW_FAILURE: 'USER_NEW_FAILURE',

  USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
  USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  USER_DELETE_FAILURE: 'USER_DELETE_FAILURE',

  USER_UPLOAD_AVATAR_REQUEST: 'USER_UPLOAD_AVATAR_REQUEST',
  USER_UPLOAD_AVATAR_SUCCESS: 'USER_UPLOAD_AVATAR_SUCCESS',
  USER_UPLOAD_AVATAR_FAILURE: 'USER_UPLOAD_AVATAR_FAILURE',

  USER_CHANGE_DATA: 'USER_CHANGE_DATA',
};

export default actionTypes;